### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by XedinUnknown** [apix/log#13]
When I try to install `^1.2.2` of this together with anything that requires `psr/log >= 2.0`, Composer fails. This is because even the last tagged version does not allow `psr/log` 2 and 3. These changes are present on `master`, however. So all that needs to be done is adding a tag.

Please 🙏

**Comment by frqnck** [comment]
Hi @XedinUnknown,

Well spotted. As per your suggestion, a new tag was added.

v1.3.0 was released and bring official support PHP >= 8. Enjoy.

Many thanks for pointing this out.

**Comment by XedinUnknown** [comment]
Thank you for the quick fix! 🙏
