### ISSUE TITLE
Mail won't send emails

### ISSUE THREAD

**Issue by mjacobus** [apix/log#2]
Hey =)

I was searching for PSR-3 loggers and I found yours. I would like to know if this is a WIP or ready to use. I did not try it out yet, but by reading the following code I concluded that the email class is still a WIP. Is it?

https//github.com/frqnck/apix-log/blob/master/src/Logger/Mail.php#L22

It seems that the `write` method is the same as the ErrorLog, so it do not actually send an email.

Cheers!

**Comment by frqnck** [comment]
Hi there,

This logger is fully functional. It does work in sending emails, etc...

The `Mail` class uses the PHP built-in [error_log](http://php.net/manual/en/function.error-log.php) function which also accept email address(es). Essentially it is using PHP's `mail()` function.

You could also extends this class and add support for a more featured mailer such as [PHPMailer](https://github.com/PHPMailer/PHPMailer), [Swiftmailer](http://swiftmailer.org), ... but generally PHP internal one is good enough.

Hope this helps you.

**Comment by mjacobus** [comment]
It does. Thank you =)

**Comment by frqnck** [comment]
Here is an implementation using PHPMailer
https://github.com/Synchro/apix-log-phpmailer
